comment: JEPA_LP_115_1brl_64_128_128_256_1024_4_4_sim_coeff_12.5_std_coeff_12.5_lr_2.4
hidden_dim: 1024
latent_dim: 256
num_layers: 4
num_steps: 4
projector_dims:
- 64
- 128
- 128
projector_type: 1brl
sim_coeff: 12.5
start_lr: 2.4
std_coeff: 12.5
