comment: JEPA_LP_344_1brl_64_128_128_512_1024_4_8_sim_coeff_12.5_std_coeff_25.0_lr_1.2
hidden_dim: 1024
latent_dim: 512
num_layers: 4
num_steps: 8
projector_dims:
- 64
- 128
- 128
projector_type: 1brl
sim_coeff: 12.5
start_lr: 1.2
std_coeff: 25.0
