comment: JEPA_LP_211_1brl_64_128_128_512_1024_4_1_sim_coeff_25.0_std_coeff_6.25_lr_0.15
hidden_dim: 1024
latent_dim: 512
num_layers: 4
num_steps: 1
projector_dims:
- 64
- 128
- 128
projector_type: 1brl
sim_coeff: 25.0
start_lr: 0.15
std_coeff: 6.25
