comment: JEPA_LP_202_1brl_64_128_128_512_1024_4_1_sim_coeff_12.5_std_coeff_12.5_lr_0.3
hidden_dim: 1024
latent_dim: 512
num_layers: 4
num_steps: 1
projector_dims:
- 64
- 128
- 128
projector_type: 1brl
sim_coeff: 12.5
start_lr: 0.3
std_coeff: 12.5
