comment: JEPA_LP_46_1brl_64_128_128_256_1024_4_2_sim_coeff_6.25_std_coeff_6.25_lr_0.15
hidden_dim: 1024
latent_dim: 256
num_layers: 4
num_steps: 2
projector_dims:
- 64
- 128
- 128
projector_type: 1brl
sim_coeff: 6.25
start_lr: 0.15
std_coeff: 6.25
