comment: JEPA_LP_88_1brl_64_128_128_256_1024_4_2_sim_coeff_25.0_std_coeff_25.0_lr_0.6
hidden_dim: 1024
latent_dim: 256
num_layers: 4
num_steps: 2
projector_dims:
- 64
- 128
- 128
projector_type: 1brl
sim_coeff: 25.0
start_lr: 0.6
std_coeff: 25.0
