seed: null
comment: null

batch_size: 256
num_workers: 8

num_epochs: 10

end_lr: 0.0
lr_num_warmup_epochs: 4
lr_decay: cosine

momentum: 0.9
weight_decay: 1.e-6
eta: 1.e-3
weight_decay_filter: True
lars_adaptation_filter: True

cov_coeff: 1.0
